services:
  - type: web
    name: rectv-pro
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.0.0
